<?php
/**
 * ConstraintApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Flagr\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\".
 *
 * The version of the OpenAPI document: 1.1.14
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Flagr\Client\Api;

use Flagr\Client\ApiException;
use Flagr\Client\Configuration;
use Flagr\Client\HeaderSelector;
use Flagr\Client\ObjectSerializer;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;

/**
 * ConstraintApi Class Doc Comment
 *
 * @category Class
 * @package  Flagr\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConstraintApi
{
    protected \GuzzleHttp\ClientInterface $client;

    protected \Flagr\Client\Configuration $config;

    protected \Flagr\Client\HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createConstraint' => [
            'application/json',
        ],
        'deleteConstraint' => [
            'application/json',
        ],
        'findConstraints' => [
            'application/json',
        ],
        'putConstraint' => [
            'application/json',
        ],
    ];

    /**
         * @param ClientInterface $client
         * @param Configuration   $config
         * @param HeaderSelector  $selector
         * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
         */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createConstraint
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Flagr\Client\Model\Constraint|\Flagr\Client\Model\Error
     */
    public function createConstraint($flag_id, $segment_id, $body, string $contentType = self::contentTypes['createConstraint'][0])
    {
        [$response] = $this->createConstraintWithHttpInfo($flag_id, $segment_id, $body, $contentType);

        return $response;
    }

    /**
     * Operation createConstraintWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Flagr\Client\Model\Constraint|\Flagr\Client\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function createConstraintWithHttpInfo($flag_id, $segment_id, $body, string $contentType = self::contentTypes['createConstraint'][0])
    {
        $request = $this->createConstraintRequest($flag_id, $segment_id, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if (\Flagr\Client\Model\Constraint::class === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if (\Flagr\Client\Model\Constraint::class !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, \Flagr\Client\Model\Constraint::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if (\Flagr\Client\Model\Error::class === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if (\Flagr\Client\Model\Error::class !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, \Flagr\Client\Model\Error::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = \Flagr\Client\Model\Constraint::class;
            if ($returnType === \SplFileObject::class) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Constraint::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Error::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createConstraintAsync
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConstraintAsync($flag_id, $segment_id, $body, string $contentType = self::contentTypes['createConstraint'][0])
    {
        return $this->createConstraintAsyncWithHttpInfo($flag_id, $segment_id, $body, $contentType)
            ->then(
                fn($response) => $response[0]
            );
    }

    /**
     * Operation createConstraintAsyncWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createConstraintAsyncWithHttpInfo($flag_id, $segment_id, $body, string $contentType = self::contentTypes['createConstraint'][0])
    {
        $returnType = \Flagr\Client\Model\Constraint::class;
        $request = $this->createConstraintRequest($flag_id, $segment_id, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createConstraint'
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createConstraintRequest($flag_id, $segment_id, $body, string $contentType = self::contentTypes['createConstraint'][0])
    {
        // verify the required parameter 'flag_id' is set
        if ($flag_id === null || (is_array($flag_id) && count($flag_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flag_id when calling createConstraint'
            );
        }
        if ($flag_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$flag_id" when calling ConstraintApi.createConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segment_id' is set
        if ($segment_id === null || (is_array($segment_id) && count($segment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segment_id when calling createConstraint'
            );
        }
        if ($segment_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$segment_id" when calling ConstraintApi.createConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createConstraint'
            );
        }


        $resourcePath = '/flags/{flagID}/segments/{segmentID}/constraints';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($flag_id !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flag_id),
                $resourcePath
            );
        }
        // path params
        if ($segment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteConstraint
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteConstraint($flag_id, $segment_id, $constraint_id, string $contentType = self::contentTypes['deleteConstraint'][0])
    {
        $this->deleteConstraintWithHttpInfo($flag_id, $segment_id, $constraint_id, $contentType);
    }

    /**
     * Operation deleteConstraintWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteConstraintWithHttpInfo($flag_id, $segment_id, $constraint_id, string $contentType = self::contentTypes['deleteConstraint'][0])
    {
        $request = $this->deleteConstraintRequest($flag_id, $segment_id, $constraint_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Error::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteConstraintAsync
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteConstraintAsync($flag_id, $segment_id, $constraint_id, string $contentType = self::contentTypes['deleteConstraint'][0])
    {
        return $this->deleteConstraintAsyncWithHttpInfo($flag_id, $segment_id, $constraint_id, $contentType)
            ->then(
                fn($response) => $response[0]
            );
    }

    /**
     * Operation deleteConstraintAsyncWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteConstraintAsyncWithHttpInfo($flag_id, $segment_id, $constraint_id, string $contentType = self::contentTypes['deleteConstraint'][0])
    {
        $returnType = '';
        $request = $this->deleteConstraintRequest($flag_id, $segment_id, $constraint_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                fn($response) => [null, $response->getStatusCode(), $response->getHeaders()],
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteConstraint'
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteConstraintRequest($flag_id, $segment_id, $constraint_id, string $contentType = self::contentTypes['deleteConstraint'][0])
    {
        // verify the required parameter 'flag_id' is set
        if ($flag_id === null || (is_array($flag_id) && count($flag_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flag_id when calling deleteConstraint'
            );
        }
        if ($flag_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$flag_id" when calling ConstraintApi.deleteConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segment_id' is set
        if ($segment_id === null || (is_array($segment_id) && count($segment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segment_id when calling deleteConstraint'
            );
        }
        if ($segment_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$segment_id" when calling ConstraintApi.deleteConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'constraint_id' is set
        if ($constraint_id === null || (is_array($constraint_id) && count($constraint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $constraint_id when calling deleteConstraint'
            );
        }
        if ($constraint_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$constraint_id" when calling ConstraintApi.deleteConstraint, must be bigger than or equal to 1.');
        }


        $resourcePath = '/flags/{flagID}/segments/{segmentID}/constraints/{constraintID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($flag_id !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flag_id),
                $resourcePath
            );
        }
        // path params
        if ($segment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segment_id),
                $resourcePath
            );
        }
        // path params
        if ($constraint_id !== null) {
            $resourcePath = str_replace(
                '{' . 'constraintID' . '}',
                ObjectSerializer::toPathValue($constraint_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation findConstraints
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findConstraints'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Flagr\Client\Model\Constraint[]|\Flagr\Client\Model\Error
     */
    public function findConstraints($flag_id, $segment_id, string $contentType = self::contentTypes['findConstraints'][0])
    {
        [$response] = $this->findConstraintsWithHttpInfo($flag_id, $segment_id, $contentType);

        return $response;
    }

    /**
     * Operation findConstraintsWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findConstraints'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Flagr\Client\Model\Constraint[]|\Flagr\Client\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function findConstraintsWithHttpInfo($flag_id, $segment_id, string $contentType = self::contentTypes['findConstraints'][0])
    {
        $request = $this->findConstraintsRequest($flag_id, $segment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Flagr\Client\Model\Constraint[]' === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Flagr\Client\Model\Constraint[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Flagr\Client\Model\Constraint[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if (\Flagr\Client\Model\Error::class === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if (\Flagr\Client\Model\Error::class !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, \Flagr\Client\Model\Error::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Flagr\Client\Model\Constraint[]';
            if ($returnType === \SplFileObject::class) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Flagr\Client\Model\Constraint[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Error::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findConstraintsAsync
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findConstraints'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findConstraintsAsync($flag_id, $segment_id, string $contentType = self::contentTypes['findConstraints'][0])
    {
        return $this->findConstraintsAsyncWithHttpInfo($flag_id, $segment_id, $contentType)
            ->then(
                fn($response) => $response[0]
            );
    }

    /**
     * Operation findConstraintsAsyncWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findConstraints'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findConstraintsAsyncWithHttpInfo($flag_id, $segment_id, string $contentType = self::contentTypes['findConstraints'][0])
    {
        $returnType = '\Flagr\Client\Model\Constraint[]';
        $request = $this->findConstraintsRequest($flag_id, $segment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findConstraints'
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['findConstraints'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function findConstraintsRequest($flag_id, $segment_id, string $contentType = self::contentTypes['findConstraints'][0])
    {
        // verify the required parameter 'flag_id' is set
        if ($flag_id === null || (is_array($flag_id) && count($flag_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flag_id when calling findConstraints'
            );
        }
        if ($flag_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$flag_id" when calling ConstraintApi.findConstraints, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segment_id' is set
        if ($segment_id === null || (is_array($segment_id) && count($segment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segment_id when calling findConstraints'
            );
        }
        if ($segment_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$segment_id" when calling ConstraintApi.findConstraints, must be bigger than or equal to 1.');
        }


        $resourcePath = '/flags/{flagID}/segments/{segmentID}/constraints';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($flag_id !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flag_id),
                $resourcePath
            );
        }
        // path params
        if ($segment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putConstraint
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Flagr\Client\Model\Constraint|\Flagr\Client\Model\Error
     */
    public function putConstraint($flag_id, $segment_id, $constraint_id, $body, string $contentType = self::contentTypes['putConstraint'][0])
    {
        [$response] = $this->putConstraintWithHttpInfo($flag_id, $segment_id, $constraint_id, $body, $contentType);

        return $response;
    }

    /**
     * Operation putConstraintWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putConstraint'] to see the possible values for this operation
     *
     * @throws \Flagr\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Flagr\Client\Model\Constraint|\Flagr\Client\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function putConstraintWithHttpInfo($flag_id, $segment_id, $constraint_id, $body, string $contentType = self::contentTypes['putConstraint'][0])
    {
        $request = $this->putConstraintRequest($flag_id, $segment_id, $constraint_id, $body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if (\Flagr\Client\Model\Constraint::class === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if (\Flagr\Client\Model\Constraint::class !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, \Flagr\Client\Model\Constraint::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                default:
                    if (\Flagr\Client\Model\Error::class === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if (\Flagr\Client\Model\Error::class !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, \Flagr\Client\Model\Error::class, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = \Flagr\Client\Model\Constraint::class;
            if ($returnType === \SplFileObject::class) {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Constraint::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        \Flagr\Client\Model\Error::class,
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putConstraintAsync
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putConstraintAsync($flag_id, $segment_id, $constraint_id, $body, string $contentType = self::contentTypes['putConstraint'][0])
    {
        return $this->putConstraintAsyncWithHttpInfo($flag_id, $segment_id, $constraint_id, $body, $contentType)
            ->then(
                fn($response) => $response[0]
            );
    }

    /**
     * Operation putConstraintAsyncWithHttpInfo
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putConstraintAsyncWithHttpInfo($flag_id, $segment_id, $constraint_id, $body, string $contentType = self::contentTypes['putConstraint'][0])
    {
        $returnType = \Flagr\Client\Model\Constraint::class;
        $request = $this->putConstraintRequest($flag_id, $segment_id, $constraint_id, $body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === \SplFileObject::class) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putConstraint'
     *
     * @param  int $flag_id numeric ID of the flag (required)
     * @param  int $segment_id numeric ID of the segment (required)
     * @param  int $constraint_id numeric ID of the constraint (required)
     * @param  \Flagr\Client\Model\CreateConstraintRequest $body create a constraint (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['putConstraint'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putConstraintRequest($flag_id, $segment_id, $constraint_id, $body, string $contentType = self::contentTypes['putConstraint'][0])
    {
        // verify the required parameter 'flag_id' is set
        if ($flag_id === null || (is_array($flag_id) && count($flag_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flag_id when calling putConstraint'
            );
        }
        if ($flag_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$flag_id" when calling ConstraintApi.putConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segment_id' is set
        if ($segment_id === null || (is_array($segment_id) && count($segment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segment_id when calling putConstraint'
            );
        }
        if ($segment_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$segment_id" when calling ConstraintApi.putConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'constraint_id' is set
        if ($constraint_id === null || (is_array($constraint_id) && count($constraint_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $constraint_id when calling putConstraint'
            );
        }
        if ($constraint_id < 1) {
            throw new \InvalidArgumentException('invalid value for "$constraint_id" when calling ConstraintApi.putConstraint, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling putConstraint'
            );
        }


        $resourcePath = '/flags/{flagID}/segments/{segmentID}/constraints/{constraintID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($flag_id !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flag_id),
                $resourcePath
            );
        }
        // path params
        if ($segment_id !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segment_id),
                $resourcePath
            );
        }
        // path params
        if ($constraint_id !== null) {
            $resourcePath = str_replace(
                '{' . 'constraintID' . '}',
                ObjectSerializer::toPathValue($constraint_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($body));
            } else {
                $httpBody = $body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
